apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
  - image: ghcr.io/shipperizer/istio/base
    custom:
      buildCommand: DOCKERFILE=docker/Dockerfile.base ./buildx.sh
      dependencies:
        dockerfile:
          path: docker/Dockerfile.base
  - image: ghcr.io/shipperizer/istio/distroless
    custom:
      buildCommand: DOCKERFILE=docker/Dockerfile.distroless ./buildx.sh
      dependencies:
        dockerfile:
          path: docker/Dockerfile.distroless
  local:
    push: true

